/* Generated By:JJTree: Do not edit this line. ALiteral.java */

package it.unifi.dsi.blitese.parser;

public abstract class ALiteral extends SimpleNode implements Expression {
  public ALiteral(int id) {
    super(id);
  }

  public ALiteral(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

//added code start here ////////////////////////////////////////////////////////

    private Token token;

    public Token getToken() {
        return token;
    }

    public void setToken(Token token) {
        this.token = token;
    }

    abstract public Object parseValue();

    public Object evaluate(RuntimeValueProvider valueProvider) {
        return parseValue();
    }

}
