/* Generated By:JJTree: Do not edit this line. BLTDEFStartScopeActivity.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFStartScopeActivity extends AScope {
  public BLTDEFStartScopeActivity(int id) {
    super(id);
  }

  public BLTDEFStartScopeActivity(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
