/* Generated By:JJTree: Do not edit this line. BLTDEFPartnerId.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFPartnerId extends SimpleNode {
  public BLTDEFPartnerId(int id) {
    super(id);
  }

  public BLTDEFPartnerId(BliteParser p, int id) {
    super(p, id);
  }

}
