/* Generated By:JJTree: Do not edit this line. BLTDEFInvParams.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFInvParams extends ABltValueHolder {
  public BLTDEFInvParams(int id) {
    super(id);
  }

  public BLTDEFInvParams(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

//added code start here ////////////////////////////////////////////////////////
}
