/* Generated By:JJTree: Do not edit this line. BLTDEFExpression.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFExpression extends SimpleNode {
  public BLTDEFExpression(int id) {
    super(id);
  }

  public BLTDEFExpression(BliteParser p, int id) {
    super(p, id);
  }

}
