/* Generated By:JJTree: Do not edit this line. BLTDEFInvParam.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFInvParam extends ABltValueHolder {
  public BLTDEFInvParam(int id) {
    super(id);
  }

  public BLTDEFInvParam(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

//added code start here ////////////////////////////////////////////////////////
}
