/* Generated By:JJTree: Do not edit this line. BLTDEFServiceDef.java */

package it.unifi.dsi.blitese.parser;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class BLTDEFServiceDef extends AServiceElement {
  public BLTDEFServiceDef(int id) {
    super(id);
  }

  public BLTDEFServiceDef(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
//added code start here ////////////////////////////////////////////////////////
  
    //map to mark the create instances recive
    private HashMap<String, BLTDEFReceiveActivity> mPortIdCreate = new HashMap<String, BLTDEFReceiveActivity>();
    private List<BLTDEFReceiveActivity> mAllCreateReceive = new ArrayList<BLTDEFReceiveActivity>();

    public boolean markAsCreateInstance(BLTDEFReceiveActivity receiveActivity) {
        
        String portId = receiveActivity.getPortId();
        receiveActivity.setCreate(true);
        mAllCreateReceive.add(receiveActivity);
        
        return null == mPortIdCreate.put(portId, receiveActivity);
        
    }

    @Override
    public boolean isCreateInstancePort(String portId) {
        return null != mPortIdCreate.get(portId);
    }

    @Override
    public List<BLTDEFReceiveActivity> getMAllCreateReceive() {
        return mAllCreateReceive;
    }


    
}
