/* Generated By:JJTree: Do not edit this line. BLTDEFPartnerId.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFPartnerId extends ABltValueHolder {
  
  public BLTDEFPartnerId(int id) {
    super(id);
  }

  public BLTDEFPartnerId(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
//added code start here ////////////////////////////////////////////////////////
    
    
    
}
