/* Generated By:JJTree: Do not edit this line. BLTDEFAddNode.java */

package it.unifi.dsi.blitese.parser;

import java.math.BigDecimal;

public class BLTDEFAddNode extends ANumericalExpression {
  public BLTDEFAddNode(int id) {
    super(id);
  }

  public BLTDEFAddNode(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

    @Override
    public Number compute(Number n1, Number n2) {
        BigDecimal d1 = new BigDecimal(n1.doubleValue());
        BigDecimal d2 = new BigDecimal(n2.doubleValue());

        return d1.add(d2);
    }
}
