/* Generated By:JJTree: Do not edit this line. BLTDEFDeployments.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFDeployments extends SimpleNode {
  public BLTDEFDeployments(int id) {
    super(id);
  }

  public BLTDEFDeployments(BliteParser p, int id) {
    super(p, id);
  }

}
