/* Generated By:JJTree: Do not edit this line. BLTDEFOperationId.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFOperationId extends SimpleNode {
  public BLTDEFOperationId(int id) {
    super(id);
  }

  public BLTDEFOperationId(BliteParser p, int id) {
    super(p, id);
  }

}
