/* Generated By:JJTree: Do not edit this line. BLTDEFServiceInstance.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFServiceInstance extends AServiceElement {
  public BLTDEFServiceInstance(int id) {
    super(id);
  }

  public BLTDEFServiceInstance(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
