/* Generated By:JJTree: Do not edit this line. BLTDEFPartnerLitId.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFPartnerLitId extends SimpleNode {
  public BLTDEFPartnerLitId(int id) {
    super(id);
  }

  public BLTDEFPartnerLitId(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }


  //added code start here ////////////////////////////////////////////////////////

    private Token token;

    public Token getToken() {
        return token;
    }

    public void setToken(Token token) {
        this.token = token;
    }

    public String getServiceName() {
        return getToken().image;
    }

}
