/* Generated By:JJTree: Do not edit this line. BLTDEFInvokeActivity.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFInvokeActivity extends SimpleNode {
  public BLTDEFInvokeActivity(int id) {
    super(id);
  }

  public BLTDEFInvokeActivity(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
    ////////////////////////////////////////////////////////////////////////////
    //added code start here
    private BLTDEFInvPartners partners;
    private BLTDEFOperationId operationId;
    private BLTDEFInvParams params;
    
    public BLTDEFInvPartners getPartners() {
        return partners;
    }

    public void setPartners(BLTDEFInvPartners partners) {
        this.partners = partners;
    }

    public BLTDEFOperationId getOperationId() {
        return operationId;
    }

    public void setOperationId(BLTDEFOperationId operationId) {
        this.operationId = operationId;
    }

    public BLTDEFInvParams getParams() {
        return params;
    }

    public void setParams(BLTDEFInvParams params) {
        this.params = params;
    }
  
}
