/* Generated By:JJTree: Do not edit this line. BLTDEFExpression.java */

package it.unifi.dsi.blitese.parser;

//TODO temporary solution extendid simple ValueHolder
public class BLTDEFExpression extends ABltValueHolder {
  public BLTDEFExpression(int id) {
    super(id);
  }

  public BLTDEFExpression(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
//added code start here ////////////////////////////////////////////////////////
}
