/* Generated By:JJTree: Do not edit this line. BLTDEFInvPartners.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFInvPartners extends SimpleNode {
  public BLTDEFInvPartners(int id) {
    super(id);
  }

  public BLTDEFInvPartners(BliteParser p, int id) {
    super(p, id);
  }

}
