/* Generated By:JJTree: Do not edit this line. BLTDEFPickActivity.java */

package it.unifi.dsi.blitese.parser;

import java.util.ArrayList;
import java.util.List;

public class BLTDEFPickActivity extends SimpleNode {
  public BLTDEFPickActivity(int id) {
    super(id);
  }

  public BLTDEFPickActivity(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  //added code start here ////////////////////////////////////////////////////////
  
    public class PickSequence {
        public BLTDEFReceiveActivity receiveActivity;
        public BLTDEFActivity activity;

        public PickSequence(BLTDEFReceiveActivity receiveActivity, BLTDEFActivity activity) {
            this.receiveActivity = receiveActivity;
            this.activity = activity;
        }
    }

    private List<PickSequence> myActions = new ArrayList<PickSequence>();

    public void addSeq(BLTDEFReceiveActivity receiveActivity, BLTDEFActivity activity) {
        myActions.add(new PickSequence(receiveActivity, activity));
    }

    public List<PickSequence> getOptions() {
        return myActions;
    }

}
