/* Generated By:JJTree: Do not edit this line. BLTDEFOrNode.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFOrNode extends ALogicExpression {
  public BLTDEFOrNode(int id) {
    super(id);
  }

  public BLTDEFOrNode(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

    @Override
    public Boolean test(Boolean b1) {
        if (b1) return Boolean.TRUE;
        else return null;
    }

    @Override
    public Boolean test(Boolean b1, Boolean b2) {
        return b1 || b2;
    }
}
