/* Generated By:JJTree: Do not edit this line. BLTDEFPartnerLitId.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFPartnerLitId extends SimpleNode {
  public BLTDEFPartnerLitId(int id) {
    super(id);
  }

  public BLTDEFPartnerLitId(BliteParser p, int id) {
    super(p, id);
  }

}
