/* Generated By:JJTree: Do not edit this line. BLTDEFActivity.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFActivity extends SimpleNode {
  public BLTDEFActivity(int id) {
    super(id);
  }

  public BLTDEFActivity(BliteParser p, int id) {
    super(p, id);
  }

}
