/* Generated By:JJTree: Do not edit this line. BLTDEFGENode.java */

package it.unifi.dsi.blitese.parser;

/**
 * >=
 * @author panks
 */
public class BLTDEFGENode extends AComparisonExpression {
  public BLTDEFGENode(int id) {
    super(id);
  }

  public BLTDEFGENode(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

    
    @Override
    public Boolean compare(Number n1, Number n2) {

        //NOT CORRECT DIFFERENT TYPE NOT HAVE NATIVE IMPLICT CONVERSION
//        Comparable c1 = (Comparable) n1;
//        Comparable c2 = (Comparable) n2;
//
//        return c1.compareTo(c2) >= 0;

        //WE USE THE MOST FINE LIVEL TO TEST (doulbe value)
        return n1.doubleValue() >= n2.doubleValue();
    }

}
