/* Generated By:JJTree: Do not edit this line. BLTDEFNumberLiteral.java */

package it.unifi.dsi.blitese.parser;

import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

public class BLTDEFNumberLiteral extends ALiteral {
  public BLTDEFNumberLiteral(int id) {
    super(id);
  }

  public BLTDEFNumberLiteral(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

//added code start here ////////////////////////////////////////////////////////
    static private final NumberFormat FORMAT = NumberFormat.getInstance(Locale.ENGLISH);

    @Override
    public Object parseValue() {
        String stringNumebr = getToken().image;

        Number n = null;
        try {
            n = FORMAT.parse(stringNumebr);
        } catch (ParseException ex) {
            Logger.getLogger(BLTDEFNumberLiteral.class.getName()).log(Level.SEVERE, null, ex);
        }

        return n;
    }
}
