/* Generated By:JJTree: Do not edit this line. BLTDEFReceiveActivity.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFReceiveActivity extends SimpleNode {
  public BLTDEFReceiveActivity(int id) {
    super(id);
  }

  public BLTDEFReceiveActivity(BliteParser p, int id) {
    super(p, id);
  }

}
