/* Generated By:JJTree: Do not edit this line. BLTDEFReceiveActivity.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFReceiveActivity extends SimpleNode {
  public BLTDEFReceiveActivity(int id) {
    super(id);
  }

  public BLTDEFReceiveActivity(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
//added code start here ////////////////////////////////////////////////////////
  
    private BLTDEFRecPartners recPartners;
    private BLTDEFOperationId operation;
    private BLTDEFRecParams params;
    
    public BLTDEFRecPartners getPartners() {
        return recPartners;
    }

    public void setPartners(BLTDEFRecPartners partners) {
        this.recPartners = partners;
    }

    public BLTDEFOperationId getOperation() {
        return operation;
    }

    public void setOperation(BLTDEFOperationId operation) {
        this.operation = operation;
    }

    public BLTDEFRecParams getParams() {
        return params;
    }

    public void setParams(BLTDEFRecParams params) {
        this.params = params;
    }
    
    public String getPortId() {
        return makePortId(getPartners().getServiceName(), getOperation().getName());
    }
    
    static public String makePortId(String serviceName, String operationName) {
        
        return serviceName + "/" + operationName;
        
    }
}
