/* Generated By:JJTree: Do not edit this line. BLTDEFProcessDefinitionMY.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFProcessDefinitionMY extends BltDefProcess {
  public BLTDEFProcessDefinitionMY(int id) {
    super(id);
  }

  public BLTDEFProcessDefinitionMY(BliteParser p, int id) {
    super(p, id);
  }

}
