/* Generated By:JJTree: Do not edit this line. BLTDEFLTNode.java */

package it.unifi.dsi.blitese.parser;

/**
 * <
 * @author panks
 */
public class BLTDEFLTNode extends AComparisonExpression {
  public BLTDEFLTNode(int id) {
    super(id);
  }

  public BLTDEFLTNode(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

    @Override
    public Boolean compare(Number n1, Number n2) {
        return n1.doubleValue() < n2.doubleValue();
    }
}
