/* Generated By:JJTree: Do not edit this line. BLTDEFNENode.java */

package it.unifi.dsi.blitese.parser;

/**
 * NOT EQUAL
 * @author panks
 */
public class BLTDEFNENode extends AComparisonExpression {
  public BLTDEFNENode(int id) {
    super(id);
  }

  public BLTDEFNENode(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

    @Override
    public Boolean compare(Number n1, Number n2) {
        return ! n1.equals(n2);
    }
}
