/* Generated By:JJTree: Do not edit this line. BLTDEFCorrelationSet.java */

package it.unifi.dsi.blitese.parser;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class BLTDEFCorrelationSet extends SimpleNode {
  public BLTDEFCorrelationSet(int id) {
    super(id);
  }

  public BLTDEFCorrelationSet(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
//added code start here ////////////////////////////////////////////////////////
  
    private Set<String> correlationSet = new HashSet<String>();

    public Set<String> getCorrelationSet() {
        return correlationSet;
    }

//    public void setCorrelationSet(Set<String> correlationSet) {
//        this.correlationSet = correlationSet;
//    }
    
    public void addVarToCorrelationSet(String var) {
        correlationSet.add(var);
    }
}
