/* Generated By:JJTree: Do not edit this line. BLTDEFDefinitionUnit.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFDefinitionUnit extends SimpleNode {
  public BLTDEFDefinitionUnit(int id) {
    super(id);
  }

  public BLTDEFDefinitionUnit(BliteParser p, int id) {
    super(p, id);
  }

}
