/* Generated By:JJTree: Do not edit this line. BLTDEFRecPartners.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFRecPartners extends SimpleNode {
  public BLTDEFRecPartners(int id) {
    super(id);
  }

  public BLTDEFRecPartners(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
//added code start here ////////////////////////////////////////////////////////
  
    private Token portToken;
//    private String portId;

    public Token getPortToken() {
        return portToken;
    }

    public void setPortToken(Token portToken) {
        this.portToken = portToken;
    }
    
    public String getPortId() {
        return portToken.image;
    }

//    public void setPortId(String portId) {
//        this.portId = portId;
//    }
    
}
