/* Generated By:JJTree: Do not edit this line. BLTDEFStartSequenceActivity.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFStartSequenceActivity extends SimpleNode {
  public BLTDEFStartSequenceActivity(int id) {
    super(id);
  }

  public BLTDEFStartSequenceActivity(BliteParser p, int id) {
    super(p, id);
  }

}
