/* Generated By:JJTree: Do not edit this line. BLTDEFEmptyActivity.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFEmptyActivity extends SimpleNode {
  public BLTDEFEmptyActivity(int id) {
    super(id);
  }

  public BLTDEFEmptyActivity(BliteParser p, int id) {
    super(p, id);
  }

}
