/* Generated By:JJTree: Do not edit this line. BLTDEFCorrelationSet.java */

package it.unifi.dsi.blitese.parser;

import java.util.ArrayList;
import java.util.List;

public class BLTDEFCorrelationSet extends SimpleNode {
  public BLTDEFCorrelationSet(int id) {
    super(id);
  }

  public BLTDEFCorrelationSet(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
//added code start here ////////////////////////////////////////////////////////
  
    private List<String> correlationSet = new ArrayList<String>();

    public List<String> getCorrelationSet() {
        return correlationSet;
    }

    public void setCorrelationSet(List<String> correlationSet) {
        this.correlationSet = correlationSet;
    }
    
    public void addVarToCorrelationSet(String var) {
        correlationSet.add(var);
    }
}
