/* Generated By:JJTree: Do not edit this line. BLTDEFRecPartners.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFRecPartners extends SimpleNode {
  public BLTDEFRecPartners(int id) {
    super(id);
  }

  public BLTDEFRecPartners(BliteParser p, int id) {
    super(p, id);
  }

}
