/* Generated By:JJTree: Do not edit this line. BLTDEFStartActivity.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFStartActivity extends BLTDEFActivity {
  public BLTDEFStartActivity(int id) {
    super(id);
  }

  public BLTDEFStartActivity(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
