/* Generated By:JJTree: Do not edit this line. /home/panks/sviluppo/progetti/blite-se/blite-se-defmodel/src/main/java/it/unifi/dsi/blitese/parser/BliteParserTreeConstants.java */

package it.unifi.dsi.blitese.parser;

public interface BliteParserTreeConstants
{
  public int JJTDEFINITIONUNIT = 0;
  public int JJTDEPLOYMENTS = 1;
  public int JJTDEPLOYMENT = 2;
  public int JJTSERVICEMY = 3;
  public int JJTPROCESSINSTANCEMY = 4;
  public int JJTPROCESSDEFINITIONMY = 5;
  public int JJTSERVICESCOPE = 6;
  public int JJTSCOPE = 7;
  public int JJTSTARTACTIVITY = 8;
  public int JJTACTIVITY = 9;
  public int JJTBASICACTIVITY = 10;
  public int JJTSTARTSEQUENCEACTIVITY = 11;
  public int JJTSEQUENCEACTIVITY = 12;
  public int JJTEMPTYACTIVITY = 13;
  public int JJTRECEIVEACTIVITY = 14;
  public int JJTINVOKEACTIVITY = 15;
  public int JJTEXITACTIVITY = 16;
  public int JJTRECPARTNERS = 17;
  public int JJTINVPARTNERS = 18;
  public int JJTPARTNERID = 19;
  public int JJTPARTNERLITID = 20;
  public int JJTOPERATIONID = 21;
  public int JJTRECPARAMS = 22;
  public int JJTINVPARAMS = 23;
  public int JJTASSIGNACTIVITY = 24;
  public int JJTEXPRESSION = 25;


  public String[] jjtNodeName = {
    "DefinitionUnit",
    "Deployments",
    "Deployment",
    "ServiceMY",
    "ProcessInstanceMY",
    "ProcessDefinitionMY",
    "ServiceScope",
    "Scope",
    "StartActivity",
    "Activity",
    "BasicActivity",
    "StartSequenceActivity",
    "SequenceActivity",
    "EmptyActivity",
    "ReceiveActivity",
    "InvokeActivity",
    "ExitActivity",
    "RecPartners",
    "InvPartners",
    "PartnerId",
    "PartnerLitId",
    "OperationId",
    "RecParams",
    "InvParams",
    "AssignActivity",
    "Expression",
  };
}
