/* Generated By:JJTree&JavaCC: Do not edit this line. BliteParserConstants.java */
package it.unifi.dsi.blitese.parser;

public interface BliteParserConstants {

  int EOF = 0;
  int INVOKE = 6;
  int RECEIVE = 7;
  int EMPTY = 8;
  int THORW = 9;
  int EXIT = 10;
  int SEQBEGIN = 11;
  int SEQEND = 12;
  int ASSIGN = 13;
  int STRING_LITERAL = 14;
  int IDENTIFIER = 15;
  int LETTER = 16;
  int PART_LETTER = 17;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"inv\"",
    "\"rcv\"",
    "\"empty\"",
    "\"throw\"",
    "\"exit\"",
    "\"seq\"",
    "\"qes\"",
    "\":=\"",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"||\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"<\"",
    "\">\"",
  };

}
