/* Generated By:JJTree: Do not edit this line. BLTDEFNotNode.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFNotNode extends SimpleNode implements Expression {
  public BLTDEFNotNode(int id) {
    super(id);
  }

  public BLTDEFNotNode(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

    public Object evaluate(RuntimeValueProvider valueProvider) {
        Expression childExp = (Expression) jjtGetChild(0);
        Object v = childExp.evaluate(valueProvider);

        Boolean b = Boolean.FALSE;
        if (v instanceof Boolean) {
            b = (Boolean) v;
        }

        return Boolean.valueOf(! b.booleanValue());
    }
}
