/* Generated By:JJTree: Do not edit this line. BLTDEFAssignActivity.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFAssignActivity extends SimpleNode {
  public BLTDEFAssignActivity(int id) {
    super(id);
  }

  public BLTDEFAssignActivity(BliteParser p, int id) {
    super(p, id);
  }

}
