/* Generated By:JJTree: Do not edit this line. BLTDEFServiceDef.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFServiceDef extends AServiceElement {
  public BLTDEFServiceDef(int id) {
    super(id);
  }

  public BLTDEFServiceDef(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
