/* Generated By:JJTree: Do not edit this line. BLTDEFSequenceActivity.java */
package it.unifi.dsi.blitese.parser;

public class BLTDEFSequenceActivity extends ABTLDEFSequenceActivity {
    public BLTDEFSequenceActivity(int id) {
        super(id);
    }

    public BLTDEFSequenceActivity(BliteParser p, int id) {
        super(p, id);
    }
    
    /** Accept the visitor. **/
    public Object jjtAccept(BliteParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

//added code start here ////////////////////////////////////////////////////////    
    
    
    public BLTDEFSequenceActivity(Node ... childs) {
        super(Integer.MIN_VALUE);
        for (int i = 0; i < childs.length; i++) {
            Node node = childs[i];
            jjtAddChild(node, i);
        }
    }

    @Override
    public String toString() {
        if (id == Integer.MIN_VALUE) return "Runtime Created Sequence Definition";
        else return super.toString();
    }
    
    
}
