/* Generated By:JJTree: Do not edit this line. BLTDEFStartFlowActivity.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFStartFlowActivity extends BLTDEFFlowActivity {
  public BLTDEFStartFlowActivity(int id) {
    super(id);
  }

  public BLTDEFStartFlowActivity(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
