/* Generated By:JJTree: Do not edit this line. BLTDEFBasicActivity.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFBasicActivity extends SimpleNode {
  public BLTDEFBasicActivity(int id) {
    super(id);
  }

  public BLTDEFBasicActivity(BliteParser p, int id) {
    super(p, id);
  }

}
