/* Generated By:JJTree: Do not edit this line. BLTDEFInvParams.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFInvParams extends SimpleNode {
  public BLTDEFInvParams(int id) {
    super(id);
  }

  public BLTDEFInvParams(BliteParser p, int id) {
    super(p, id);
  }

}
