/* Generated By:JJTree: Do not edit this line. BLTDEFReceiveActivity.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFReceiveActivity extends SimpleNode {
  public BLTDEFReceiveActivity(int id) {
    super(id);
  }

  public BLTDEFReceiveActivity(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
//added code start here ////////////////////////////////////////////////////////
  
    private BLTDEFRecPartners recPartners;

    public BLTDEFRecPartners getPartners() {
        return recPartners;
    }

    public void setPartners(BLTDEFRecPartners partners) {
        this.recPartners = partners;
    }
    
}
