/* Generated By:JJTree: Do not edit this line. BLTDEFProcessInstanceMY.java */
package it.unifi.dsi.blitese.parser;

public class BLTDEFProcessInstanceMY extends BltDefProcess {

    public BLTDEFProcessInstanceMY(int id) {
        super(id);
    }

    public BLTDEFProcessInstanceMY(BliteParser p, int id) {
        super(p, id);
    }

    @Override
    public void jjtSetParent(Node n) {
        super.jjtSetParent(n);
        BLTDEFServiceMY _parent = (BLTDEFServiceMY)n;
        _parent.addDefProcess(this);
    }
}
