/* Generated By:JJTree: Do not edit this line. BLTDEFInvokeActivity.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFInvokeActivity extends SimpleNode {
  public BLTDEFInvokeActivity(int id) {
    super(id);
  }

  public BLTDEFInvokeActivity(BliteParser p, int id) {
    super(p, id);
  }

}
