/* Generated By:JJTree: Do not edit this line. BLTDEFInvPartners.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFInvPartners extends SimpleNode {
  public BLTDEFInvPartners(int id) {
    super(id);
  }

  public BLTDEFInvPartners(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
    ////////////////////////////////////////////////////////////////////////////
    //added code start here
  
}
