/* Generated By:JJTree: Do not edit this line. BLTDEFRecParams.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFRecParams extends SimpleNode {
  public BLTDEFRecParams(int id) {
    super(id);
  }

  public BLTDEFRecParams(BliteParser p, int id) {
    super(p, id);
  }

}
