/* Generated By:JJTree: Do not edit this line. BLTDEFDeployment.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFDeployment extends SimpleNode {
  public BLTDEFDeployment(int id) {
    super(id);
  }

  public BLTDEFDeployment(BliteParser p, int id) {
    super(p, id);
  }

}
