/* Generated By:JJTree: Do not edit this line. BLTDEFStartActivity.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFStartActivity extends SimpleNode {
  public BLTDEFStartActivity(int id) {
    super(id);
  }

  public BLTDEFStartActivity(BliteParser p, int id) {
    super(p, id);
  }

}
