/* Generated By:JJTree: Do not edit this line. BLTDEFEmptyActivity.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFEmptyActivity extends SimpleNode {
  public BLTDEFEmptyActivity(int id) {
    super(id);
  }

  public BLTDEFEmptyActivity(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

//added code start here ////////////////////////////////////////////////////////  
    
    public BLTDEFEmptyActivity() {
        super(Integer.MIN_VALUE);
    }
  
    @Override
    public String toString() {
        if (id == Integer.MIN_VALUE) return "Runtime Created Empty Definition";
        else return super.toString();
    }

}
