/* Generated By:JJTree: Do not edit this line. BLTDEFStringLiteral.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFStringLiteral extends ALiteral {
  public BLTDEFStringLiteral(int id) {
    super(id);
  }

  public BLTDEFStringLiteral(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

//added code start here ////////////////////////////////////////////////////////
    @Override
    public Object parseValue() {
        String s = getToken().image;

        return s;
    }
}
