/* Generated By:JJTree: Do not edit this line. BLTDEFServiceScope.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFServiceScope extends AScope {
  public BLTDEFServiceScope(int id) {
    super(id);
  }

  public BLTDEFServiceScope(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
//added code start here ////////////////////////////////////////////////////////  
}
