/* Generated By:JJTree: Do not edit this line. BLTDEFExitActivity.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFExitActivity extends SimpleNode {
  public BLTDEFExitActivity(int id) {
    super(id);
  }

  public BLTDEFExitActivity(BliteParser p, int id) {
    super(p, id);
  }

}
