/* Generated By:JJTree: Do not edit this line. BLTDEFSequenceActivity.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFSequenceActivity extends ABTLDEFSequenceActivity {
  public BLTDEFSequenceActivity(int id) {
    super(id);
  }

  public BLTDEFSequenceActivity(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
