/* Generated By:JJTree: Do not edit this line. BLTDEFBoundId.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFBoundId extends ABltId {
  public BLTDEFBoundId(int id) {
    super(id);
  }

  public BLTDEFBoundId(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

    
  
//added code start here
        
}
