/* Generated By:JJTree: Do not edit this line. BLTDEFVarId.java */

package it.unifi.dsi.blitese.parser;


public class BLTDEFVarId extends ABltId {
  public BLTDEFVarId(int id) {
    super(id);
  }

  public BLTDEFVarId(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

//added code start here
  
}
