/* Generated By:JJTree: Do not edit this line. BLTDEFServiceScope.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFServiceScope extends SimpleNode {
  public BLTDEFServiceScope(int id) {
    super(id);
  }

  public BLTDEFServiceScope(BliteParser p, int id) {
    super(p, id);
  }

}
