/* Generated By:JJTree: Do not edit this line. BLTDEFThrowActivity.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFThrowActivity extends SimpleNode {
  public BLTDEFThrowActivity(int id) {
    super(id);
  }

  public BLTDEFThrowActivity(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
//added code start here ////////////////////////////////////////////////////////  
  
    public BLTDEFThrowActivity() {
        super(Integer.MIN_VALUE);
    }
  
    @Override
    public String toString() {
        if (id == Integer.MIN_VALUE) return "Runtime Created Throw Definition";
        else return super.toString();
    }  
}
