/* Generated By:JJTree: Do not edit this line. BLTDEFScope.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFScope extends SimpleNode {
  public BLTDEFScope(int id) {
    super(id);
  }

  public BLTDEFScope(BliteParser p, int id) {
    super(p, id);
  }

}
