/* Generated By:JJTree: Do not edit this line. BLTDEFStartPickActivity.java */

package it.unifi.dsi.blitese.parser;

public class BLTDEFStartPickActivity extends BLTDEFPickActivity {
  public BLTDEFStartPickActivity(int id) {
    super(id);
  }

  public BLTDEFStartPickActivity(BliteParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BliteParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
