/*
 * EnvComponent.java
 *
 * Created on 6 novembre 2008, 17.16
 */
package it.unifi.dsi.blitese.localenv.gui.env;

import it.unifi.dsi.blitese.localenv.IncompatibleCompUnitException;
import it.unifi.dsi.blitese.localenv.gui.BliteTreeCellRederer;
import it.unifi.dsi.blitese.localenv.gui.env.nodes.EnvBaseNode;
import it.unifi.dsi.blitese.parser.BLTDEFCompilationUnit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPopupMenu;
import javax.swing.tree.TreePath;

/**
 * Swing Container for the tree structure of Blite Local Runtime Enviroment
 * 
 * 
 * @author  panks
 */
public class EnvComponent extends javax.swing.JPanel {
//    private LocalEnvironment environment;
    private EnvModel envModel;

    /** Creates new form EnvComponent */
    public EnvComponent() {
        initComponents();

//        environment = new LocalEnvironment();
        envModel = new EnvModel(); //EnvModel(environment);
        jTree.setModel(envModel);
        jTree.setCellRenderer(new BliteTreeCellRederer());
        jTree.addMouseListener(new PopupTrigger()); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTree.setName("jTree"); // NOI18N
        jScrollPane1.setViewportView(jTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree;
    // End of variables declaration//GEN-END:variables
    
    public void addCUtoEnviroment(BLTDEFCompilationUnit compilationUnit) throws IncompatibleCompUnitException {
        envModel.addCUtoEnviroment(compilationUnit);
    }

    //Mouse Adapter. It Trigger the popup Menu on tree nodes.
    class PopupTrigger extends MouseAdapter {
        
        @Override
        public void mousePressed(MouseEvent e) {
            maybeShowPopup(e);
        }
        
        @Override
        public void mouseReleased(MouseEvent e) {
            maybeShowPopup(e);
        }

        private void maybeShowPopup(MouseEvent e) {
        
            if (e.isPopupTrigger()) {
                int x = e.getX();
                int y = e.getY();
                TreePath path = jTree.getPathForLocation(x, y);
                if (path != null) {
                    EnvBaseNode node = (EnvBaseNode) path.getLastPathComponent();
                    JPopupMenu jpm = node.getPopupMenu();
                    if (jpm != null) {
                        jpm.show(e.getComponent(), x, y);
                    }
                }
            }
        }
    }
}
